name: Deploy to EKS

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Build Docker Image
        run: docker build -t apl-back:v3 .  --platform linux/amd64
      
      - name: Push Docker Image to Docker Hub
        run: docker push apl-back:v3

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up kubectl
        uses: kubernetes/cli@v2
        with:
          kubectl-version: '1.27.7'

      - name: Deploy to EKS
        run: kubectl apply -f kube/apl/
